export enum CompanyType {
  LIMITED_LIABILITY = 'LIMITED_LIABILITY',
  PUBLIC_LISTED = 'PUBLIC_LISTED',
  LIMITED_COMPANY = 'LIMITED_COMPANY',
  UNLIMITED_COMPANY = 'UNLIMITED_COMPANY',
  NON_PROFIT = 'NON_PROFIT',
  PARTNERSHIP = 'PARTNERSHIP',
  CORPORATION = 'CORPORATION',
  PRIVATE_COMPANY_LIMITED = 'PRIVATE_COMPANY_LIMITED',
  SMALL_BUSINESS = 'SMALL_BUSINESS',
}
