export const environmentConstants = {
  environment: {
    NODE_ENV: 'NODE_ENV',
    SERVER_PORT: 'SERVER_PORT',
    SERVER_HOST: 'SERVER_HOST',
    DB_ENGINE: 'DB_ENGINE',
    DB_HOST: 'DB_HOST',
    DB_PORT: 'DB_PORT',
    DB_USER: 'DB_USER',
    DB_PASSWORD: 'DB_PASSWORD',
    DB_NAME: 'DB_NAME',
    // password encryption
    ENCRYPTION_KEY: 'ENCRYPTION_KEY',
    // password hashing
    SALT_WORK_FACTOR: 'SALT_WORK_FACTOR',
    // JWT
    ACCESS_TOKEN_SECRET: 'ACCESS_TOKEN_SECRET',
    ACCESS_TOKEN_TIME_TO_LIVE: 'ACCESS_TOKEN_TIME_TO_LIVE',
    REFRESH_TOKEN_SECRET: 'REFRESH_TOKEN_SECRET',
    REFRESH_TOKEN_TIME_TO_LIVE: 'REFRESH_TOKEN_TIME_TO_LIVE',
  },
};
